---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "43"
year: "2023"
contributor: 
- Karsten Schuldt
title: "Werden die Öffentlichen Bibliotheken von zwei unterschiedlichen Gruppen benutzt? Ein konzeptionelles Modell"
abstract: "Anhand eines Beispiels zeigt der Artikel, welche Konsequenzen ein soziologisch orientiertes Denken für die Bibliothekspraxis haben könnte. Es wird eine These über die Nutzung Öffentlicher Bibliotheken entwickelt, Evidenzen für diese gesammelt und anschliessend ein konzeptionelles Modell erstellt, mit dem diese These überprüft werden kann. Es wird postuliert, dass es sei unterschiedliche Gruppen von Nutzer*innen gibt, eine bestandsbezogene und eine raumbezogene. Zusätzlich wird diskutiert, welche Konsequenzen für die Praxis Öffentlicher Bibliotheken gezogen werden könnten, wenn sich die These als richtig herausstellt."
abstractalt: "Using an example, the article shows what consequences sociologically-oriented thinking could have for library practice. It develops a thesis about the use of public libraries, collects evidence for it and  creates a conceptual model with which this thesis can be tested. It is postulated that there are different groups of users, one collection-related and one space-related. In addition, it discusses possible consequences for the practice of public libraries if the thesis proves to be correct."
pdf: "main.pdf"
doi: "10.18452/27069"
date: 2023-07-27
comments: false
sharing: true
footer: true

---