---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "43"
year: "2023"
contributor: 
- Mirco Limpinsel-Pesavento
title: "Welche Funktion erfüllt die Bibliothek der Zukunft? Bibliotheken als wirtschaftliche Systeme"
abstract: "Der Beitrag geht hervor aus einer bibliothekswissenschaftlichen Abschlussarbeit, in der es um bibliothekarische Organisationsentwicklung aus systemtheoretischer Perspektive ging. Anstatt die Arbeit langweilig zusammenzufassen, wird ein Aspekt diskutiert, der sich aus der systemtheoretischen Annahme ergibt, dass es sich bei Bibliotheken um Teile des Wirtschaftssystems handelt. Insbesondere vor dem Hintergrund der Digitalisierungskrise lassen sich aus dieser Perspektive instruktive Impulse ableiten."
doi: "10.18452/..."
date: 2023-07-21
comments: false
sharing: true
footer: true

---