---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "43"
year: "2023"
contributor: 
- "Vorstand LIBREAS-Verein"
title: "In eigener Sache: Bericht über die Aktivitäten des LIBREAS-Vereins 2021/2022"
pdf: "https://doi.org/10.18452/27072"
doi: "10.18452/27072"
date: 2023-08-04
comments: false
sharing: true
footer: true

---