---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "43"
year: "2023"
contributor: 
- Redaktion LIBREAS
title: "Editorial #43: Soziologie der Bibliothek"
pdf: "https://doi.org/10.18452/27066"
doi: "10.18452/27066"
date: 2022-08-20
comments: false
sharing: true
footer: true

---