---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "43"
year: "2023"
contributor: 
- Julia Bartlewski
title: "Erhebung zum Frauenanteil in Leitungspositionen an deutschen Bibliotheken"
abstract: "Geschlechterverhältnisse auf dem Arbeitsmarkt sind Gegenstand zahlreicher Debatten und im Zuge eines sozialen Wandels in das kollektive Bewusstsein gerückt. Der Arbeitsbereich <q>Bibliothek</q> ist ein frauendominiertes Feld mit einem Frauenanteil von über 74%. Interessanterweise liegen jedoch keine aktuellen umfassenden statistischen Auswertungen über Frauen in Leitungspositionen an deutschen Bibliotheken vor. Vor dem Hintergrund der Leitfrage, wie hoch der Anteil von Frauen in der obersten Hierarchieebene an deutschen Bibliotheken ist, präsentiert der vorliegende Artikel die Ergebnisse einer quantitativen Erhebung. Diese werden in einen theoretischen Kontext eingebettet, in dem Forschungsaspekte aus verschiedenen wissenschaftlichen Disziplinen, wie der Geschlechter- oder Organisationsforschung, vorangestellt werden. Dieser Beitrag beruht auf einer Masterarbeit aus dem Jahr 2021 am Institut für Bibliotheks- und Informationswissenschaft der Humboldt Universität zu Berlin."
abstractalt: "Gender proportions in the employment sector are the subject of numerous debates and have moved into the collective awareness as a result of social change. The 'library' work area is a female-dominated field with a share of women of over 74%. Interestingly, however, there are no current detailed statistical evaluations of women in management positions in German libraries. Against the background of the main question regarding the proportion of women at the top hierarchical level in German libraries, this article presents the results of a quantitative survey. These are embedded in a theoretical context in which research aspects from various scientific disciplines, such as gender or organizational research, are presented. This article is based on a master's thesis written in 2021 at the Institute of Library and Information Science at the Humboldt Universität zu Berlin."
pdf: "https://doi.org/10.18452/27071"
doi: "10.18452/27071"
date: 2023-08-20
comments: false
sharing: true
footer: true

---