---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "43"
year: "2023"
contributor: 
- Alexandra C. Roth
title: "Mediensoziologie"
abstract: "Der Begriff Mediensozialisation verweist auf den Sachverhalt, dass sich Prozesse der Vergesellschaftung und der Persönlichkeitsentwicklung zunehmend in der Interaktion mit Medien vollziehen. Die Auseinandersetzung mit Webangeboten, Büchern, TV und anderen Medien trägt mit dazu bei, dass der einzelne Mensch gesellschaftliche Strukturen, Normen et cetera verinnerlicht. Begreift man Medien als wesentlichen Teil des Alltagslebens und damit verbunden als Sozialisationsprozesse beeinflussend, so ergeben sich daraus interessante Impulse für die bibliothekarische Praxis. Der vorliegende Artikel zeigt schlaglichtartig auf, inwiefern die Mediensozialisationsforschung dazu beitragen kann, Bibliotheksdienstleistungen und -angebote weiterzuentwickeln."
abstractalt: "<q>Media socialization</q> points out that the interaction with media is gaining in importance for the process of socialization and for the development of personality. Dealing with the web, books, television and other media contributes to internalizing social structures, standards et cetera. If media is understood as an indispensable part of daily life and, subsequently, as an important factor for socialization, we can receive impulses for the library praxis. This article highlights how the research on media socialization could help librarians to develop or to refine their services and offers."
pdf: "main.pdf"
doi: "10.18452/27070"
date: 2023-08-04
comments: false
sharing: true
footer: true

---