---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "43"
year: "2023"
contributor: 
- Linda Freyberg
title: "Eine soziologische Perspektive auf Smart Libraries"
abstract: "In diesem Beitrag wird eine Definition des Konzeptes der Smart Libraries gegeben und vor dem Hintergrund technologischer Entwicklungen im Spannungsfeld zwischen Kontinuität und Wandel eingeordnet. Dabei werden (technik-) philosophische und soziologische Theorien eingebunden, die größere Fragen aufwerfen und zur weiteren Lektüre einladen."
pdf: "https://doi.org/10.18452/27067"
doi: "10.18452/27067"
date: 2023-07-21
comments: false
sharing: true
footer: true

---