---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "43"
year: "2023"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #12 (Frühling bis Sommer 2023)"
pdf: "main.pdf"
doi: "10.18452/..."
date: 2023-07-22
comments: false
sharing: true
footer: true

---